# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/signalc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/signalc.proto\x12\x07signalc\"\x1f\n\x0c\x42\x61seResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xe1\x01\n\x19SignalRegisterKeysRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x16\n\x0eregistrationId\x18\x02 \x01(\x05\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\x05\x12\x19\n\x11identityKeyPublic\x18\x04 \x01(\x0c\x12\x10\n\x08preKeyId\x18\x05 \x01(\x05\x12\x0e\n\x06preKey\x18\x06 \x01(\x0c\x12\x16\n\x0esignedPreKeyId\x18\x07 \x01(\x05\x12\x14\n\x0csignedPreKey\x18\x08 \x01(\x0c\x12\x1d\n\x15signedPreKeySignature\x18\t \x01(\x0c\")\n\x15SignalKeysUserRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"\xde\x01\n\x16SignalKeysUserResponse\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x16\n\x0eregistrationId\x18\x02 \x01(\x05\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\x05\x12\x19\n\x11identityKeyPublic\x18\x04 \x01(\x0c\x12\x10\n\x08preKeyId\x18\x05 \x01(\x05\x12\x0e\n\x06preKey\x18\x06 \x01(\x0c\x12\x16\n\x0esignedPreKeyId\x18\x07 \x01(\x05\x12\x14\n\x0csignedPreKey\x18\x08 \x01(\x0c\x12\x1d\n\x15signedPreKeySignature\x18\t \x01(\x0c\"F\n\x0ePublishRequest\x12\x10\n\x08senderId\x18\x01 \x01(\t\x12\x11\n\treceiveId\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\x0c\"-\n\x19SubscribeAndListenRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"0\n\x0bPublication\x12\x10\n\x08senderId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x32\x89\x03\n\x15SignalKeyDistribution\x12N\n\x11RegisterBundleKey\x12\".signalc.SignalRegisterKeysRequest\x1a\x15.signalc.BaseResponse\x12W\n\x14GetKeyBundleByUserId\x12\x1e.signalc.SignalKeysUserRequest\x1a\x1f.signalc.SignalKeysUserResponse\x12\x46\n\tSubscribe\x12\".signalc.SubscribeAndListenRequest\x1a\x15.signalc.BaseResponse\x12\x44\n\x06Listen\x12\".signalc.SubscribeAndListenRequest\x1a\x14.signalc.Publication0\x01\x12\x39\n\x07Publish\x12\x17.signalc.PublishRequest\x1a\x15.signalc.BaseResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.signalc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASERESPONSE._serialized_start=32
  _BASERESPONSE._serialized_end=63
  _SIGNALREGISTERKEYSREQUEST._serialized_start=66
  _SIGNALREGISTERKEYSREQUEST._serialized_end=291
  _SIGNALKEYSUSERREQUEST._serialized_start=293
  _SIGNALKEYSUSERREQUEST._serialized_end=334
  _SIGNALKEYSUSERRESPONSE._serialized_start=337
  _SIGNALKEYSUSERRESPONSE._serialized_end=559
  _PUBLISHREQUEST._serialized_start=561
  _PUBLISHREQUEST._serialized_end=631
  _SUBSCRIBEANDLISTENREQUEST._serialized_start=633
  _SUBSCRIBEANDLISTENREQUEST._serialized_end=678
  _PUBLICATION._serialized_start=680
  _PUBLICATION._serialized_end=728
  _SIGNALKEYDISTRIBUTION._serialized_start=731
  _SIGNALKEYDISTRIBUTION._serialized_end=1124
# @@protoc_insertion_point(module_scope)
