# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/opaque.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/opaque.proto\x12\x06opaque\"8\n\x13RegistrationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"(\n\x14RegistrationResponse\x12\x10\n\x08response\x18\x01 \x01(\x0c\"3\n\x0f\x46inalizeRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06record\x18\x02 \x01(\x0c\"&\n\x10\x46inalizeResponse\x12\x12\n\nregistered\x18\x01 \x01(\x08\"6\n\x11\x43redentialRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\"&\n\x12\x43redentialResponse\x12\x10\n\x08response\x18\x01 \x01(\x0c\"7\n\x15\x41uthenticationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04\x61uth\x18\x02 \x01(\x0c\"\'\n\x16\x41uthenticationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"5\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\'\n\x13VerifyTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\x87\x03\n\x14OpaqueAuthentication\x12I\n\x0cRegisterUser\x12\x1b.opaque.RegistrationRequest\x1a\x1c.opaque.RegistrationResponse\x12@\n\x0bStoreRecord\x12\x17.opaque.FinalizeRequest\x1a\x18.opaque.FinalizeResponse\x12K\n\x12RequestCredentials\x12\x19.opaque.CredentialRequest\x1a\x1a.opaque.CredentialResponse\x12M\n\x0c\x41uthenticate\x12\x1d.opaque.AuthenticationRequest\x1a\x1e.opaque.AuthenticationResponse\x12\x46\n\x0bVerifyToken\x12\x1a.opaque.VerifyTokenRequest\x1a\x1b.opaque.VerifyTokenResponseb\x06proto3')



_REGISTRATIONREQUEST = DESCRIPTOR.message_types_by_name['RegistrationRequest']
_REGISTRATIONRESPONSE = DESCRIPTOR.message_types_by_name['RegistrationResponse']
_FINALIZEREQUEST = DESCRIPTOR.message_types_by_name['FinalizeRequest']
_FINALIZERESPONSE = DESCRIPTOR.message_types_by_name['FinalizeResponse']
_CREDENTIALREQUEST = DESCRIPTOR.message_types_by_name['CredentialRequest']
_CREDENTIALRESPONSE = DESCRIPTOR.message_types_by_name['CredentialResponse']
_AUTHENTICATIONREQUEST = DESCRIPTOR.message_types_by_name['AuthenticationRequest']
_AUTHENTICATIONRESPONSE = DESCRIPTOR.message_types_by_name['AuthenticationResponse']
_VERIFYTOKENREQUEST = DESCRIPTOR.message_types_by_name['VerifyTokenRequest']
_VERIFYTOKENRESPONSE = DESCRIPTOR.message_types_by_name['VerifyTokenResponse']
RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUEST,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.RegistrationRequest)
  })
_sym_db.RegisterMessage(RegistrationRequest)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONRESPONSE,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.RegistrationResponse)
  })
_sym_db.RegisterMessage(RegistrationResponse)

FinalizeRequest = _reflection.GeneratedProtocolMessageType('FinalizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINALIZEREQUEST,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.FinalizeRequest)
  })
_sym_db.RegisterMessage(FinalizeRequest)

FinalizeResponse = _reflection.GeneratedProtocolMessageType('FinalizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINALIZERESPONSE,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.FinalizeResponse)
  })
_sym_db.RegisterMessage(FinalizeResponse)

CredentialRequest = _reflection.GeneratedProtocolMessageType('CredentialRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALREQUEST,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.CredentialRequest)
  })
_sym_db.RegisterMessage(CredentialRequest)

CredentialResponse = _reflection.GeneratedProtocolMessageType('CredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALRESPONSE,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.CredentialResponse)
  })
_sym_db.RegisterMessage(CredentialResponse)

AuthenticationRequest = _reflection.GeneratedProtocolMessageType('AuthenticationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONREQUEST,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.AuthenticationRequest)
  })
_sym_db.RegisterMessage(AuthenticationRequest)

AuthenticationResponse = _reflection.GeneratedProtocolMessageType('AuthenticationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONRESPONSE,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.AuthenticationResponse)
  })
_sym_db.RegisterMessage(AuthenticationResponse)

VerifyTokenRequest = _reflection.GeneratedProtocolMessageType('VerifyTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYTOKENREQUEST,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.VerifyTokenRequest)
  })
_sym_db.RegisterMessage(VerifyTokenRequest)

VerifyTokenResponse = _reflection.GeneratedProtocolMessageType('VerifyTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYTOKENRESPONSE,
  '__module__' : 'proto.opaque_pb2'
  # @@protoc_insertion_point(class_scope:opaque.VerifyTokenResponse)
  })
_sym_db.RegisterMessage(VerifyTokenResponse)

_OPAQUEAUTHENTICATION = DESCRIPTOR.services_by_name['OpaqueAuthentication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATIONREQUEST._serialized_start=30
  _REGISTRATIONREQUEST._serialized_end=86
  _REGISTRATIONRESPONSE._serialized_start=88
  _REGISTRATIONRESPONSE._serialized_end=128
  _FINALIZEREQUEST._serialized_start=130
  _FINALIZEREQUEST._serialized_end=181
  _FINALIZERESPONSE._serialized_start=183
  _FINALIZERESPONSE._serialized_end=221
  _CREDENTIALREQUEST._serialized_start=223
  _CREDENTIALREQUEST._serialized_end=277
  _CREDENTIALRESPONSE._serialized_start=279
  _CREDENTIALRESPONSE._serialized_end=317
  _AUTHENTICATIONREQUEST._serialized_start=319
  _AUTHENTICATIONREQUEST._serialized_end=374
  _AUTHENTICATIONRESPONSE._serialized_start=376
  _AUTHENTICATIONRESPONSE._serialized_end=415
  _VERIFYTOKENREQUEST._serialized_start=417
  _VERIFYTOKENREQUEST._serialized_end=470
  _VERIFYTOKENRESPONSE._serialized_start=472
  _VERIFYTOKENRESPONSE._serialized_end=511
  _OPAQUEAUTHENTICATION._serialized_start=514
  _OPAQUEAUTHENTICATION._serialized_end=905
# @@protoc_insertion_point(module_scope)
